receivers:
  otlp:
    protocols:
      grpc:
      http:
  filelog:
    include: [ /var/log/minishop/*.log ]
    start_at: beginning
    operators:
      - type: json_parser
        parse_from: body
        timestamp:
          parse_from: body.time
          layout: '%Y-%m-%dT%H:%M:%S.%fZ'
      - type: severity_parser
        parse_from: body.level
      - type: move
        from: body
        to: attributes

processors:
  batch: {}

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      attributes:
        level: level
        service: service
        env: env
        component: component
        use_case: use_case
    default_labels_enabled:
      exporter: false
      job: false
      instance: false
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [loki]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
