receivers:
  otlp:
    protocols:
      grpc:
      http:
  filelog:
    include: [ /var/log/minishop/*.log ]
    start_at: beginning
    operators:
      - type: json_parser
        parse_from: body
        timestamp:
          parse_from: body.time
          layout_type: gotime
          layout: '2006-01-02T15:04:05.999999999Z07:00'
      - type: severity_parser
        parse_from: body.level
      # Move selected fields from body -> attributes for labeling
      - type: move
        from: body.level
        to: attributes.level
      - type: move
        from: body.service
        to: attributes.service
      - type: move
        from: body.env
        to: attributes.env
      - type: move
        from: body.component
        to: attributes.component
      - type: move
        from: body.use_case
        to: attributes.use_case
      # Set final log body to the message string if present
      - type: move
        from: body.msg
        to: body

processors:
  batch: {}

exporters:
  otlphttp/loki:
    endpoint: http://loki:3100
    logs_endpoint: http://loki:3100/otlp/v1/logs
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [otlphttp/loki]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
